### ISSUE TITLE
Getting the site to work

### ISSUE THREAD

**Issue by RealistikDash** [RlSEN/bannedcho#3]
Alright, so I'm new to apache so don't call me out on my stupidity.

So for the osu.ppy.sh.conf and other files what needs to be changed (except the server directory in osu.ppy.sh.conf). Do you need to add extra text to it? Copying them directly doesn't work (of course) so what do I do?

Once again sorry if this is a stupid question.

**Comment by KadePcGames** [comment]
Nothing. You can just change the root directory of the default config to /var/www/html/osu.ppy.sh/

**Comment by RealistikDash** [comment]
I fixed myself.
