### ISSUE TITLE
503 Service Unavailable on osu.[domain]

### ISSUE THREAD

**Issue by RealistikDash** [RlSEN/bannedcho#5]
So, after reaching the config stage, I have been unable to get to the config without a 503 Service Unavailable error. After some research, I (think) it is some proxy error but I am not sure. Any help?
![image](https://user-images.githubusercontent.com/36131887/48663410-0b440f00-ea90-11e8-92fb-228ec4229f03.png)

Thanks in advance.

**Comment by troke12** [comment]
i got a same problem, for c.domain.com but osu.domain.com it's work properly but can't make a account
