### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by Mar0xy** [RlSEN/bannedcho#7]
It is just stuck on processing login request and this also happend why can't it just continue

**Comment by RealistikDash** [comment]
Any fix?

**Comment by LordDamionDevil** [comment]
Sadly no I had to go with a different solution I recommend using this instead https://github.com/light-ripple/Ripple-Auto-Installer

**Comment by Mar0xy** [comment]
> Any fix?

Sadly no I had to go with a different solution I recommend using this instead https://github.com/light-ripple/Ripple-Auto-Installer

**Comment by RealistikDash** [comment]
Ah alright. Cheers

**Comment by Mar0xy** [comment]
So that repo was deleted after he merged my pull idk why but because I knew something like that would happen I made a Organization with all the repos that are being used and I will still provide updates to the script via it Organization: https://github.com/osuinitalize Script: https://github.com/osuinitalize/Ripple-Installer
